### ISSUE TITLE
의도와 다른 API가 호출될 수있는 문제

### ISSUE THREAD

**Issue by puleugo** [Media-XI/artscope-backend#161]
경로에 동적인 정보인 `username`이 들어가는 경우, 다른 API와 경로 충돌이 일어날 수 있어보입니다.

# 예시
`username`이 "profile"인 경우.
```
GET /api/members/{username}
```
위 API을 호출했을 때 아래 API가 호출됨.
```
GET /api/members/profile
```

---
실제 운영 도중에 특정 기능이 마비되어 버리기 때문에 꽤 크리티컬할 것으로 예상됩니다.

**Comment by haroya01** [comment]
```java
GET /api/members/profile
```
해당 경로를 삭제하고 
의무적으로 반드시 username을 받도록 하는것은 어떨까요?
```java
    @Operation(summary = "회원 프로필 조회", description = "[USER] 회원의 프로필을 조회합니다.")
    @GetMapping("/{username}")
```

**Comment by Hoon9901** [comment]
내 정보 조회 api를 authController로 이관하는게 좋아보입니다.

/api/auth/me
